version: '3.4'

services:
  nginx:
    image: nginx:1.16.0-alpine
    tty: true
    env_file: .env
    command: ash -c "
      envsubst '$$API_GATEWAY_PORT' < /etc/nginx/conf.d/local.conf.template > /etc/nginx/conf.d/local.conf &&
      envsubst '$$API_GATEWAY_PORT' < /etc/nginx/conf.d/dev.conf.template > /etc/nginx/conf.d/dev.conf &&
      nginx -t &&
      nginx -g 'daemon off;'"
    ports:
      - 80:80
    volumes:
      - ./nginx/log/:/var/log/nginx
      - ./nginx/conf.d/local.conf.template:/etc/nginx/conf.d/local.conf.template:ro
      - ./nginx/conf.d/dev.conf.template:/etc/nginx/conf.d/dev.conf.template:ro
      - ./packages/web-patients/:/usr/share/nginx/html/web-patients:ro
      - ./packages/web-doctors/:/usr/share/nginx/html/web-doctors:ro

  pgweb:
    image: sosedoff/pgweb:0.11.2
    ports:
      - 8081:8081

  api-gateway:
    image: node:12.6.0
    env_file: .env
    working_dir: /apollo-hospitals/packages/api
    command: bash -c "
      while ((! curl -s http://profiles-service/graphql) || (! curl -s http://doctors-service/graphql)) > /dev/null;
      do echo waiting for services to start...; sleep 5;
      done;
      node api-gateway.bundle.js"
    volumes:
      - ./:/apollo-hospitals:cached
    depends_on:
      - profiles-service
      - doctors-service
      - nginx

  profiles-service:
    image: node:12.6.0
    env_file: .env
    working_dir: /apollo-hospitals/packages/api
    command: bash -c "
      while ! < /dev/tcp/profiles-db/5432; do echo waiting for profiles-db...; sleep 5; done;
      node profiles-service.bundle.js"
    volumes:
      - ./:/apollo-hospitals:cached
    depends_on:
      - profiles-db

  profiles-db:
    image: postgres:10.8-alpine
    volumes:
      - ./packages/api/init-profiles-db.sql:/docker-entrypoint-initdb.d/init.sql

  doctors-service:
    image: node:12.6.0
    env_file: .env
    working_dir: /apollo-hospitals/packages/api
    command: bash -c "node doctors-service.bundle.js"
    volumes:
      - ./:/apollo-hospitals:cached
