version: '3.4'

services:
  nginx:
    image: nginx:1.16.0-alpine
    tty: true
    env_file: .env
    command: ash -c "
      envsubst '$$NODE_ENV $$API_GATEWAY_PORT $$WEB_PATIENTS_PORT $$WEB_DOCTORS_PORT' < /etc/nginx/conf.d/development.conf.template > /etc/nginx/conf.d/development.conf &&
      nginx -t &&
      nginx -g 'daemon off;'"
    ports:
      - 80:80
    volumes:
      # Docker runs as root and so these files cannot be deleted by our deployment user, just disable mounting logs for now
      # - ./nginx/log/:/var/log/nginx
      - ./nginx/conf.d/development.conf.template:/etc/nginx/conf.d/development.conf.template:ro
      - ./packages/web-patients/:/usr/share/nginx/html/web-patients:ro
      - ./packages/web-doctors/:/usr/share/nginx/html/web-doctors:ro

  pgweb:
    image: sosedoff/pgweb:0.11.2
    ports:
      - 8081:8081

  api-gateway:
    image: node:12.6.0
    env_file: .env
    working_dir: /apollo-hospitals/packages/api
    command: bash -c "
      while ((! curl -s http://profiles-service/graphql) || (! curl -s http://doctors-service/graphql) || (! curl -s http://consults-service/graphql)) > /dev/null;
      do echo waiting for services to start...; sleep 5;
      done;
      node api-gateway.bundle.js"
    volumes:
      - ./:/apollo-hospitals:cached
    depends_on:
      - profiles-service
      - doctors-service
      - consults-service
      - nginx

  profiles-service:
    image: node:12.6.0
    env_file: .env
    working_dir: /apollo-hospitals/packages/api
    command: bash -c "
      while ! < /dev/tcp/profiles-db/${PROFILES_DB_PORT};
      do echo waiting for profiles-db...; sleep 5;
      done;
      node profiles-service.bundle.js"
    volumes:
      - ./:/apollo-hospitals:cached
    depends_on:
      - profiles-db

  profiles-db:
    image: postgres:10.8-alpine
    volumes:
      - ./packages/api/init-profiles-db.sql:/docker-entrypoint-initdb.d/init.sql

  doctors-service:
    image: node:12.6.0
    env_file: .env
    working_dir: /apollo-hospitals/packages/api
    command: bash -c "
      while ! < /dev/tcp/doctors-db/${DOCTORS_DB_PORT};
      do echo waiting for doctors-db...; sleep 5;
      done;
      node doctors-service.bundle.js"
    volumes:
      - ./:/apollo-hospitals:cached
    depends_on:
      - doctors-db

  doctors-db:
    image: postgres:10.8-alpine
    volumes:
      - ./packages/api/init-doctors-db.sql:/docker-entrypoint-initdb.d/init.sql

  consults-service:
    image: node:12.6.0
    env_file: .env
    working_dir: /apollo-hospitals/packages/api
    command: bash -c "
      while  (!(< /dev/tcp/consults-db/${CONSULTS_DB_PORT}) || !(/dev/tcp/consults-db/${DOCTORS_DB_PORT}));
      do echo waiting for consults-db and doctors-db...; sleep 5;
      done;
      node consults-service.bundle.js"
    volumes:
      - ./:/apollo-hospitals:cached
    depends_on:
      - consults-db
      - doctors-db

  consults-db:
    image: postgres:10.8-alpine
    volumes:
      - ./packages/api/src/consults-service/init-consults-db.sql:/docker-entrypoint-initdb.d/init.sql
