import { StyleSheet, Dimensions, Platform } from 'react-native';
import { theme } from '@aph/mobile-doctors/src/theme/theme';
import { isIphoneX } from 'react-native-iphone-x-helper';

const { width, height } = Dimensions.get('screen');
export const AudioVideoStyles = StyleSheet.create({
  mainViewStyle: {
    flex: 1,
    backgroundColor: 'black',
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    elevation: 1000,
    zIndex: 100,
  },
  minimizedMainViewStyle: {
    flex: 1,
    backgroundColor: 'black',
    position: 'absolute',
    top: 88,
    right: 20,
    width: 155,
    height: 205,
    elevation: 10,
    borderRadius: 10,
    zIndex: 101,
    shadowColor: theme.colors.SHADOW_GRAY,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.6,
    shadowRadius: 4,
  },
  imageContainer: {
    flex: 1,
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 101,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.whiteColor(0.6),
  },
  imageContainerMinimized: {
    flex: 1,
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 101,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.whiteColor(0.6),
    borderRadius: 10,
    overflow: 'hidden',
  },
  patientImageStyle: {
    height: width,
    width: width,
    backgroundColor: theme.colors.WHITE,
  },
  patientImageMinimizedStyle: {
    width: 155,
    height: 205,
    backgroundColor: theme.colors.WHITE,
  },
  placeHolderLoaderStyle: {
    height: width,
    width: width,
    alignItems: 'center',
    backgroundColor: theme.colors.WHITE,
  },
  placeHolderLoaderMinimizedStyle: {
    width: 155,
    height: 205,
    alignItems: 'center',
    backgroundColor: theme.colors.whiteColor(0.6),
  },
  placeHolderImageStyle: {
    height: width,
    width: width,
    alignItems: 'center',
    backgroundColor: theme.colors.WHITE,
    resizeMode: 'contain',
  },
  placeHolderImageMimimizedStyle: {
    width: 155,
    height: 205,
    alignItems: 'center',
    backgroundColor: theme.colors.WHITE,
    resizeMode: 'contain',
  },
  chatIconContainer: {
    position: 'absolute',
    top: 44,
    left: 20,
    zIndex: 106,
  },
  chatIconDotStyle: {
    left: -20,
    top: -15,
    height: 88,
    width: 88,
  },
  buttonContainer: {
    position: 'absolute',
    bottom: isIphoneX() ? 32 : 16,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-start',
    width: width,
    zIndex: 106,
  },
  buttomMinimize: {
    position: 'absolute',
    bottom: 16,
    left: 16,
    right: 16,
    width: 123,
    zIndex: 106,
    flexDirection: 'row',
    justifyContent: 'space-between',
    elevation: 10,
  },
  iconShadowEffect: {
    borderRadius: 100,
    shadowColor: theme.colors.SHADOW_GRAY,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.6,
    shadowRadius: 4,
    backgroundColor: theme.colors.WHITE,
    elevation: 5,
  },
  miniIconStyle: {
    width: 40,
    height: 40,
  },
  dotStyle: {
    backgroundColor: theme.colors.NOTIFICATION_DOT,
    width: 16,
    height: 16,
    borderRadius: 8,
    position: 'absolute',
    top: 0,
    right: 0,
    zIndex: 1,
  },
  nameContainer: {
    position: 'absolute',
    marginHorizontal: 20,
    marginTop: 44,
    width: width - 40,
    zIndex: 104,
    justifyContent: 'center',
    alignItems: 'center',
  },
  nameContainerMinimized: {
    position: 'absolute',
    width: 155,
    zIndex: 104,
    justifyContent: 'center',
    alignItems: 'center',
  },
  nameText: {
    color: theme.colors.WHITE,
    ...theme.fonts.IBMPlexSansSemiBold(20),
    elevation: 5,
    zIndex: 105,
    maxWidth: width / 1.5,
    textAlign: 'center',
  },
  timerText: {
    color: theme.colors.WHITE,
    ...theme.fonts.IBMPlexSansSemiBold(12),
    zIndex: 105,
    elevation: 5,
    textAlign: 'center',
  },
  subscriberStyle: {
    width: width,
    height: height,
  },
  subscriberMinimizedStyle: {
    width: 155,
    height: 205,
    borderRadius: 10,
  },
  publisherStyle: {
    position: 'absolute',
    top: isIphoneX() ? 74 : 44,
    right: 20,
    width: 148,
    height: 112,
    zIndex: 103,
    borderRadius: 30,
  },
  publisherMinimizedStyle: {
    position: 'absolute',
    top: 1,
    right: 1,
    width: 1,
    height: 1,
    zIndex: 103,
    borderRadius: 10,
  },
  alertContainer: {
    backgroundColor: 'white',
    paddingTop: 2,
    paddingBottom: Platform.OS === 'ios' ? 3 : 5,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginTop: 2,
    marginHorizontal: 16,
    borderRadius: 100,
  },
  alertText: {
    color: theme.colors.APP_RED,
    ...theme.fonts.IBMPlexSansSemiBold(12),
    zIndex: 105,
    elevation: 5,
    textAlign: 'center',
  },
  exoToastContainer: {
    backgroundColor: theme.colors.APP_RED,
    paddingVertical: 5,
    marginRight: 16,
    position: 'absolute',
    bottom: 90,
  },
  exoCloseContainer: {
    borderWidth: 1,
    borderColor: theme.colors.WHITE,
    borderRadius: 100,
    marginRight: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
