export const NeedHelp = [
  {
    category: 'Pharmacy',
    id: 'pharmacy',
    orderRelatedIndices: [0, 1, 2, 3, 4, 5, 6, 7, 8],
    options: [
      'I want to return my order',
      'Excess amount was charged to me by Delivery Executive',
      'I have issues in order delivered!',
      'I have prescription related queries (Invalid/ Order cancelled)',
      'I need to know my refund status',
      'I need to know why my order was cancelled',
      'I would like to cancel the order!',
      'I would like to know the Delivery status of my order.',
      'Inappropriate attitude & behaviour of Delivery Executive',
      'I was not able to place the order due to technical errors',
      'My money got deducted but no order confirmation received',
    ],
  },
  {
    category: 'Virtual/Online Consult',
    id: 'virtualOnlineConsult',
    orderRelatedIndices: [0, 1, 2, 3, 4, 5, 6, 7],
    options: [
      'Consultation ended, Doctor has not replied to my query over 24 hours',
      'I did not receive invoice/ receipt of my appointment',
      'I faced technical issues during/after booking an appointment',
      'I haven’t received the prescription',
      'I need to know my refund status',
      'I want to reschedule/cancel my appointment ',
      'Improper behaviour/attitude of doctor or staff',
      'The doctor did not start the consultation call on time',
      'I am unable to book an appointment (slot not available/ Doctor not listed)',
      'My money got deducted but no confirmation on the doctor appointment',
    ],
  },
  {
    category: 'Health Records',
    id: 'healthRecords',
    options: [
      'Add multiple UHID’s linked to other mobile numbers',
      'Delay in responses to queries',
      'Incomplete health records',
      'Issues in downloading the records',
      'No / Wrong UHID',
      'No records available for linked UHID',
      'Personal details are not editable',
      'Unable to see my reports',
      'Unable to add family members',
    ],
  },
  {
    category: 'Physical Consult',
    id: 'physicalConsult',
    options: [
      'App appointment dishonored at confirmed time slot',
      'Application issues(bandwidth & payment errors)',
      'Behavior and attitude of the doctor',
      "Can't find doctor’s name in respective list",
      'Delayed prescription',
      'Doctor not available',
      'Long waiting time for physical consult',
      'No past / upcoming consultation details',
      'No updates on delays, reschedules or cancellations of the consult',
      'Payment issues',
      'Require reschedule',
      'Refund required',
      'Discount / Promotions / Voucher issues',
    ],
  },
  {
    category: 'Feedback',
    id: 'feedback',
    options: [
      'Feedback on app',
      'Feedback on consultation',
      'Feedback on health records',
      'Feedback on medicine deliver',
    ],
  },
  {
    category: 'Diagnostics',
    id: 'diagnostics',
    options: [
      'Delay in sample Pick-up collection, Need urgent help',
      'I need to know my refund status',
      'Issue In Order Confirmation (Payment etc.)',
      'I Need to Reschedule Pick up time',
      'Report Not Received',
      'Wrong Report Received',
      'My order was cancelled without prior Information',
      'High Listing Price on app or website',
      'Sample Pick Up Staff Related feedback',
      'I need to Cancel my pick up',
    ],
  },
  {
    category: 'Unsubscribe',
    id: 'unsubscribe',
    options: ['Marketing SMSes', 'Marketing Push Notifications', 'Both'],
  },
  {
    category: 'HealthyLife (HDFC)',
    id: 'healthyLifeHdfc',
    options: [
      'Coupon related',
      'Concierge Services',
      'Digitization of Health Records',
      'Covid Services',
      'OneApollo Membership',
      'Doctor on Call',
      'Early Access to Offers & Sampling of New health products',
      'Free Delivery',
      'Base Diabetes Management Program',
      'Advanced Diabetes Management Program Trial',
      'Activating Membership',
      'Membership Upgrade',
      'Membership Downgrade',
    ],
  },
  {
    category: 'Circle Membership',
    id: 'circleMembership',
    options: [
      'Details about Circle Membership',
      'Regarding Circle Benefits',
      'Plans available for Circle Membership',
      'Signing Up for Circle Membership',
      'Buying Circle Membership using OneApollo Health Credits',
      'About Circle Cashback',
      'How to use Circle Cashback',
      'Membership Cancellation',
      'Changing Membership Plan',
      'How to get free delivery with Circle',
      'Covid Care Benefit with Circle',
      'Regarding Digitization of Patient Health Records',
      'Regarding Doctor on Call',
      'Regarding Advanced Diabetes Management Program',
      'Special Offers and Discounts with Circle Membership',
    ],
  },
];
