apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-pvc-nginxlogs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 20Gi