apiVersion: apps/v1

kind: Deployment
metadata:
  name: diagnostics-deploy
spec:
  selector:
    matchLabels:
      app: diagnostics
  template:
    metadata:
      labels:
        app: diagnostics
    spec:
      containers:
      - name: diagnostics
        image: apollodev.azurecr.io/apollodev-diagnostics-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4006
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: 250m
            memory: 1Gi
        volumeMounts:
        - name: diagnosticsapplogs
          mountPath: "/apollo-diagnostics-service/dist/access-logs/"
        - name: diagnosticserrorlogs
          mountPath: "/apollo-diagnostics-service/dist/error-logs/"
      volumes:
      - name: diagnosticsapplogs
        persistentVolumeClaim:
          claimName: azurefile-pvc-accesslogs
      - name: diagnosticserrorlogs
        persistentVolumeClaim:
          claimName: azurefile-pvc-errorlogs
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
