apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:6.8.6
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: applogs
          mountPath: "/apollo-hospitals/packages/api/access-logs/"
        - name: errorlogs
          mountPath: "/apollo-hospitals/packages/api/error-logs/"
      volumes:
      - name: config
        configMap:
          defaultMode: 0755
          name: filebeat-config
      - name: applogs
        persistentVolumeClaim:
          claimName: azurefile-pvc-accesslogs
      - name: errorlogs
        persistentVolumeClaim:
          claimName: azurefile-pvc-errorlogs
