apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /apollo-hospitals/packages/api/access-logs/*.log
        - /apollo-hospitals/packages/api/paymentlogs/info/*.log
        - /apollo-hospitals/packages/api/kaleyra-logs/*.log
        - /apollo-hospitals/packages/api/pharmalogs/*.txt
        - /apollo-subscription-service/dist/access-logs/*
        - /apollo-diagnostics-service/dist/access-logs/*
      fields:
         service: AppAccessLogs
         type: AKS-Access-log
         beat.name: aksapplog
    - type: log
      enabled: true
      paths:
        - /apollo-hospitals/packages/api/error-logs/*.log
        - /apollo-hospitals/packages/api/paymentlogs/error/*.log
        - /apollo-hospitals/packages/api/paymentlogs/debug/*.log
        - /apollo-hospitals/packages/api/debug-logs/*.log
        - /apollo-subscription-service/dist/error-logs/*
        - /apollo-diagnostics-service/dist/error-logs/*
      fields:
         service: AppErrorLogs
         type: AKS-Error-log
         beat.name: aksapplog
    setup.kibana:
        host: "104.211.246.75:5601"
    output.logstash:
        hosts: ["104.211.246.75:5044"]
