apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deploy
spec:
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: apollodev.azurecr.io/apollodev-pmtimage:latest
        command: ["node"]
        args: ["server.js"]
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: 250m
            memory: 1Gi
        volumeMounts:
        - name: paymenterrorlogs
          mountPath: "/apollo-hospitals/packages/api/paymentlogs/error/"
        - name: paymentdebuglogs
          mountPath: "/apollo-hospitals/packages/api/paymentlogs/debug/"
      volumes:
      - name: paymenterrorlogs
        persistentVolumeClaim:
          claimName: azurefile-pvc-errorlogs
      - name: paymentdebuglogs
        persistentVolumeClaim:
          claimName: azurefile-pvc-accesslogs

      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
