apiVersion: apps/v1

kind: Deployment
metadata:
  name: subscriptions-deploy
spec:
  selector:
    matchLabels:
      app: subscriptions
  template:
    metadata:
      labels:
        app: subscriptions
    spec:
      containers:
      - name: subscriptions
        image: apollodev.azurecr.io/apollodev-subscriptions-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: 250m
            memory: 1Gi
        volumeMounts:
        - name: subscriptionsapplogs
          mountPath: "/apollo-subscription-service/dist/access-logs/"
        - name: subscriptionserrorlogs
          mountPath: "/apollo-subscription-service/dist/error-logs/"
      volumes:
      - name: subscriptionsapplogs
        persistentVolumeClaim:
          claimName: azurefile-pvc-accesslogs
      - name: subscriptionserrorlogs
        persistentVolumeClaim:
          claimName: azurefile-pvc-errorlogs
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
