export const generalHelpSections = [
  {
    category: 'Pharmacy',
    options: [
      'Area pharmacy store not found on app',
      'Cancel the medicine order',
      'Delay in pharmacy order',
      'Difference in quantity of medicine delivered',
      'Excess amount charged on delivery',
      'Inappropriate attitude and behavior of pharmacy staff',
      'Incorrect medicines',
      'Issues in order confirmations',
      'Medicines not delivered',
      'Order cancelled, no refund',
      'Orders cancelled without any information',
      'Payment issues in online pharmacy',
      'Software not user-friendly',
      'Updates in order delivery or status of the order',
    ],
  },
  {
    category: 'Online Consult',
    options: [
      'Application issues (bandwidth & payment errors)',
      'Behavior and attitude of the doctor',
      'Delay in consult',
      'Delayed prescription',
      'Doctor not available',
      'How to consult virtually – demo video',
      'No past / upcoming consultation details',
      'No updates on delays, reschedules or cancellations of the consult',
      'Require reschedule',
      'Payment issues',
    ],
  },
  {
    category: 'Health Records',
    options: [
      'Add multiple UHID’s linked to other mobile numbers',
      'Delay in responses to queries',
      'Incomplete health records',
      'Issues in downloading the records',
      'No / Wrong UHID',
      'No records available for linked UHID',
      'Personal details are not editable',
      'Unable to see my reports',
    ],
  },
  {
    category: 'Physical Consult',
    options: [
      'App appointment dishonored at confirmed time slot',
      'Application issues(bandwidth & payment errors)',
      'Behavior and attitude of the doctor',
      "Can't find doctor’s name in respective list",
      'Delayed prescription',
      'Doctor not available',
      'Long waiting time for physical consult',
      'No past / upcoming consultation details',
      'No updates on delays, reschedules or cancellations of the consult',
      'Payment issues',
      'Require reschedule',
    ],
  },
  {
    category: 'Feedback',
    options: [
      'Feedback on app',
      'Feedback on consultation',
      'Feedback on health records',
      'Feedback on medicine deliver',
    ],
  },
  {
    category: 'Diagnostics',
    options: [
      'Excess amount related',
      'Issues in order confirmation',
      'Payment issues while ordering',
      'Pickup cancelled without any information',
      'Pickup cancelled, no refund',
      'Report not received',
      'Require reschedule',
      'Sample pick up related',
      'Sample pick up staff related',
      'Wrong report received',
    ],
  },
];
