import { Symptoms } from './Symptoms';
import { LifeStyle } from './LifeStyle';
import { Vital } from './Vital';
import { HealthVault } from './HealthVault';
import { DoctorsNotes } from './DoctorsNotes';
import { Diagnosis } from './Diagnosis';
import { MedicinePrescription } from './MedicinePrescription';
import { DiagnosticPrescription } from './DiagnosticPrescription';
import { FollowUp } from './FollowUp';
import { OtherInstructions } from './OtherInstructions';
import { RefferalCode } from './RefferalCode';

export { LifeStyle };
export { Vital };
export { Symptoms };
export { HealthVault };
export { DoctorsNotes };
export { Diagnosis };
export { MedicinePrescription };
export { DiagnosticPrescription };
export { FollowUp };
export { OtherInstructions };
export { RefferalCode };
